import { InMemoryDbService } from 'angular-in-memory-web-api';
import { IMovies } from '../app/movies/movies';

export class MovieData implements InMemoryDbService {

  createDb() {
    const movies: IMovies[] = [
      {
        Title: "Baahubali: The Beginning",
        id: 1,
        Year: "2015",
        Rated: "R",
        "imdbRating": "6.2",
        Released: "09 Jul 2015",
        Runtime: "159 min",
        Genre: "Action, Drama",
        Director: "S.S. Rajamouli",
        Writer: "Vijayendra Prasad (story by), S.S. Rajamouli (screenplay by), C.H. Vijay Kumar (telugu dialogue), Ajay Kumar (telugu dialogue), Madhan Karky (tamil dialogue), Manoj Muntashir (hindi dialogue)",
        Actors: "Prabhas, Rana Daggubati, Ramya Krishnan, Sathyaraj",
        Plot: "When Sanga and her husband, part of a tribe living around the province of Mahismathi, save a drowning infant, little do they know the background of the infant or what the future holds for him. The kid grows up to as Shivudu, a free-spirit wanting to explore the mountains and in the process learns of his roots and then realizes the whole purpose of his life and ends up confronting the mighty Bhallala Deva!",
        Language: "Telugu, Tamil, Hindi",
        Country: "India",
        Awards: "22 wins & 12 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYWVlMjVhZWYtNWViNC00ODFkLTk1MmItYjU1MDY5ZDdhMTU3XkEyXkFqcGdeQXVyODIwMDI1NjM@.jpg",

      },
      {
        id: 2,
        Title: "Girls Trip",
        Year: "2017",
        Rated: "R",
        "imdbRating": "5.2",
        Released: "21 Jul 2017",
        Runtime: "122 min",
        Genre: "Adventure, Comedy, Drama",
        Director: "Malcolm D. Lee",
        Writer: "Erica Rivinoja (story by), Kenya Barris (story by), Tracy Oliver (story by), Kenya Barris (screenplay by), Tracy Oliver (screenplay by)",
        Actors: "Regina Hall, Queen Latifah, Jada Pinkett Smith, Tiffany Haddish",
        Plot: "When four lifelong friends travel to New Orleans for the annual Essence Festival, sisterhoods are rekindled, wild sides are rediscovered, and there's enough dancing, drinking, brawling, and romancing to make the Big Easy blush.",
        Language: "English",
        Country: "USA, Canada",
        Awards: "10 wins & 32 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjMwNTEzODUwMV5BMl5BanBnXkFtZTgwNjE5NjA5MjI@.jpg",
      },
      {
        id: 3,
        Title: "The Boss Baby",
        Year: "2017",
        Rated: "PG",
        "imdbRating": "6.2",
        Released: "31 Mar 2017",
        Runtime: "97 min",
        Genre: "Animation, Adventure, Comedy, Family, Fantasy",
        Director: "Tom McGrath",
        Writer: "Michael McCullers, Marla Frazee (based on the book by)",
        Actors: "Alec Baldwin, Steve Buscemi, Jimmy Kimmel, Lisa Kudrow",
        Plot: "Seven-year-old Tim Templeton has always been a boy of an overactive imagination, and for the past seven years, life was all peaches for him, getting all the love and affection from his caring parents. However, life will never be the same and Tim won't be the centre of attention anymore as the arrival of an improbable new brother named Boss Baby, dressed in a black suit complete with a tie and a briefcase, will shortly rob him of all love, as he takes over the whole Templetons' house. Nevertheless, although this may be true, soon, Tim and the new Boss in a diaper will need to put differences aside and join forces, as a sneaky scheme involving the head of Puppy Co. threatens to tilt the balance of power towards their insidiously adorable furry antagonists, not to mention that the next Pet Convention is in only two days.. Brothers, hurry up.",
        Language: "English, Spanish",
        Country: "USA",
        Awards: "Nominated for 1 Oscar. Another 1 win & 19 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTg5MzUxNzgxNV5BMl5BanBnXkFtZTgwMTM2NzQ3MjI@.jpg",
      },
      {
        id: 4,
        Title: "Game Night",
        Year: "2018",
        Rated: "R",
        "imdbRating": "6.2",
        Released: "23 Feb 2018",
        Runtime: "100 min",
        Genre: "Action, Comedy, Crime, Mystery",
        Director: "John Francis Daley, Jonathan Goldstein",
        Writer: "Mark Perez",
        Actors: "Jason Bateman, Rachel McAdams, Kyle Chandler, Sharon Horgan",
        Plot: "A group of friends who meet regularly for game nights find themselves entangled in a real-life mystery when the shady brother of one of them is seemingly kidnapped by dangerous gangsters.",
        Language: "English",
        Country: "USA",
        Awards: "N/A",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjI3ODkzNDk5MF5BMl5BanBnXkFtZTgwNTEyNjY2NDM@.jpg",

      },
      {
        id: 5,
        Title: "Blockers",
        Year: "2018",
        Rated: "R",
        "imdbRating": "6.2",
        Released: "06 Apr 2018",
        Runtime: "102 min",
        Genre: "Comedy",
        Director: "Kay Cannon",
        Writer: "Brian Kehoe, Jim Kehoe",
        Actors: "Leslie Mann, John Cena, Ike Barinholtz, Kathryn Newton",
        Plot: "Three parents try to stop their daughters from losing their virginity on prom night.",
        Language: "English",
        Country: "USA",
        Awards: "1 nomination.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjE0ODIzNjkzMl5BMl5BanBnXkFtZTgwODQ3MzU4NDM@.jpg",

      },
      {
        id: 6,
        Title: "Deadpool",
        Year: "2016",
        Rated: "R",
        "imdbRating": "6.2",
        Released: "12 Feb 2016",
        Runtime: "108 min",
        Genre: "Action, Adventure, Comedy, Sci-Fi",
        Director: "Tim Miller",
        Writer: "Rhett Reese, Paul Wernick",
        Actors: "Ryan Reynolds, Karan Soni, Ed Skrein, Michael Benyaer",
        Plot: "This is the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
        Language: "English",
        Country: "USA",
        Awards: "Nominated for 2 Golden Globes. Another 27 wins & 73 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@.jpg",

      },
      {
        id: 7,
        Title: "Life of the Party",
        Year: "2018",
        Rated: "PG-13",
        "imdbRating": "6.2",
        Released: "11 May 2018",
        Runtime: "105 min",
        Genre: "Comedy",
        Director: "Ben Falcone",
        Writer: "Melissa McCarthy, Ben Falcone",
        Actors: "Melissa McCarthy, Matt Walsh, Molly Gordon, Ben Falcone",
        Plot: "After her husband abruptly asks for a divorce, a middle-aged mother returns to college in order to complete her degree.",
        Language: "English",
        Country: "USA",
        Awards: "N/A",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTkzOTk0MjYwM15BMl5BanBnXkFtZTgwNTE5ODQxNTM@.jpg",

      },
      {
        id: 8,
        Title: "Crazy Rich Asians",
        Year: "2018",
        Rated: "PG-13",
        "imdbRating": "6.2",
        Released: "15 Aug 2018",
        Runtime: "120 min",
        Genre: "Comedy, Drama, Romance",
        Director: "Jon M. Chu",
        Writer: "Peter Chiarelli (screenplay by), Adele Lim (screenplay by), Kevin Kwan (based on the novel \"Crazy Rich Asians\" by)",
        Actors: "Constance Wu, Henry Golding, Michelle Yeoh, Gemma Chan",
        Plot: "This contemporary romantic comedy, based on a global bestseller, follows native New Yorker Rachel Chu to Singapore to meet her boyfriend's family.",
        Language: "English, Mandarin, Cantonese, Hokkien, French, Malay",
        Country: "USA",
        Awards: "N/A",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTYxNDMyOTAxN15BMl5BanBnXkFtZTgwMDg1ODYzNTM@.jpg",

      },
      {
        id: 9,
        Title: "Dirty Grandpa",
        Year: "2016",
        Rated: "R",
        "imdbRating": "6.2",
        Released: "22 Jan 2016",
        Runtime: "102 min",
        Genre: "Comedy",
        Director: "Dan Mazer",
        Writer: "John Phillips",
        Actors: "Robert De Niro, Zac Efron, Zoey Deutch, Aubrey Plaza",
        Plot: "Jason Kelly, the grandson of Dick Kelly, loses his grandmother about two weeks before his wedding to Meredith. He tries to assist his grandfather and console him for his loss, but was rather tricked into a spring break road trip; chasing youth once again. with the help of Shadia and Lenore, the two men go on an adventure they'll never forget.",
        Language: "English",
        Country: "USA",
        Awards: "2 wins & 11 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMzk0NzkyNDk2M15BMl5BanBnXkFtZTgwNDczOTU3NzE@.jpg",

      },
      {
        id: 10,
        Title: "Bad Moms",
        Year: "2016",
        Rated: "R",
        "imdbRating": "6.2",
        Released: "29 Jul 2016",
        Runtime: "100 min",
        Genre: "Comedy",
        Director: "Jon Lucas, Scott Moore",
        Writer: "Jon Lucas, Scott Moore",
        Actors: "Mila Kunis, Kathryn Hahn, Kristen Bell, Christina Applegate",
        Plot: "Amy has a seemingly perfect life - a great marriage, over-achieving kids, a beautiful home and a career. However, she's overworked, over-committed and exhausted to the point that she's about to snap. Fed up, she joins forces with two other over-stressed moms on a quest to liberate themselves from conventional responsibilities - going on a wild, un-mom-like binge of long overdue freedom, fun and self-indulgence - putting them on a collision course with PTA Queen Bee Gwendolyn and her clique of devoted perfect moms.",
        Language: "English",
        Country: "USA",
        Awards: "3 wins & 5 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMjIwNzE5MTgwNl5BMl5BanBnXkFtZTgwNjM4OTA0OTE@.jpg",
      }

    ]
    return {movies};

  }
}
